CNPM/Controllers/ClothesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CNPM.Models;

namespace CNPM.Controllers
{
    public class ClothesController : Controller
    {
        // GET: Clothes
        CSDLWEBEntity data = new CSDLWEBEntity();
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult AnubisVer2(int id)
        {
            var sp = data.SanPhams.Where(a => a.MaSP == id);
            return View(sp);
        }
        public ActionResult AoKhoac(int id)
        {
            var sp = data.SanPhams.Where(a => a.MaSP == id);
            return View(sp);
        }
        public ActionResult SoMi(int id)
        {
            var sp = data.SanPhams.Where(a => a.MaSP == id);
            return View(sp);
        }
        public ActionResult QuanDai(int id)
        {
            var sp = data.SanPhams.Where(a => a.MaSP == id);
            return View(sp);
        }
        public ActionResult QuanShort(int id)
        {
            var sp = data.SanPhams.Where(a => a.MaSP == id);
            return View(sp);
        }
    }
}

CNPM/Controllers/HomeController.cs
using CNPM.Models;
using System;
using System.Collections.Generic;
using System.Data.Linq;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CNPM.Controllers
{
    public class HomeController : Controller
    {
        CSDLWEBEntity data = new CSDLWEBEntity();
        public ActionResult Index()
        {
            
            ViewBag.sanPham = data.SanPhams.OrderBy(a => a.MaSP).Take(2).ToList();

            return View();
        }
      

        public ActionResult Ao()
        {


            ViewBag.ao = data.SanPhams.OrderBy(a => a.MaSP).ToList();
            return View();
        }

        public ActionResult Quan()
        {
            ViewBag.quan = data.SanPhams.OrderBy(a => a.MaSP).ToList();

            return View();
        }
        public ActionResult GioiThieu()
        {
            return View();
        }
  
    }
}

CNPM/Views/Home/Ao.cshtml
@using CNPM.Models
@{
    ViewBag.Title = "Ao";
    List<SanPham> ao = ViewBag.ao;
}

<div class="container">
    
      
    <div class="row" style="text-align:center">
        <h2 style="color:blue; background-color:yellow"><b><i>Áo Thun</i></b></h2>
        @foreach (var i in ao)
        {
            if (i.MaDanhMuc == 1)

            {

                <div class="col-sm-3">
                    <a href="@Url.Action("AnubisVer2","Clothes", new { id = @i.MaSP})"> <img class="img-fluid" src="~/fonts/img/aothun/@i.HinhAnh" /></a>
                    <p>@i.TenSP</p>
                    <div>
                       
                    </div>
                </div>
            }
        }
       
    </div>
    <div class="row" style="text-align:center">
        <h2 style="color:blue; background-color:yellow"><b><i>Áo Khoác</i></b></h2>
        @foreach (var i in ao)
        {
            if (i.MaDanhMuc == 2)
            {
                <div class="col-sm-3">
                   <a href="@Url.Action("AoKhoac","Clothes",new { id = i.MaSP })"><img class="img-fluid" src="~/fonts/img/aokhoac/@i.HinhAnh" /></a>
                    <p>@i.TenSP</p>
                </div>
            }


        }

    </div>
    <div class="row" style="text-align:center">
        <h2 style="color:blue; background-color:yellow"><b><i>Áo Sơ Mi</i></b></h2>
        @foreach (var i in ao)
        {
            if (i.MaDanhMuc == 3)
            {
                <div class="col-sm-3">
                    <a href="@Url.Action("SoMi","Clothes",new { id = i.MaSP })">
                        <img class="img-fluid" src="~/fonts/img/aosomi/@i.HinhAnh" /> </a>
                        <p>@i.TenSP</p>
</div>
            }


        }

    </div>
   

</div>

CNPM/Views/Home/GioiThieu.cshtml
@{
    ViewBag.Title = "GioiThieu";
}

<div class="container" style="text-align:center">
    <h1><b>Công Nghệ Phần Mềm</b></h1>
    <h2><b>Tên Đồ Án: Website Giới Thiệu Quần Áo</b></h2>
    <h2><b>Tên Giảng Viên: ThS Dương Thành Phết</b></h2>
    <h2><b>Tên Thành Viên:<br />Mai Xuân Cường <br />Trần Khánh Duy<br />Quàng Văn Dương</b></h2>
</div>

CNPM/Views/Home/Index.cshtml
@using CNPM.Models;

@{
    ViewBag.Title = "Home Page";
    List<SanPham> product = ViewBag.sanPham;
}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<section class="carousel">
    <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img class="d-block w-100" src="~/fonts/img/img-hotdeal/b10ed13d-af32-0100-5b15-001790aed777.jpg" alt="First slide">
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" style="width:1201px ; height:690px"  src="~/fonts/img/img-hotdeal/0bea69a9-4fc6-4c9a-8606-be3bd93b2720-MOBANAOTHUN.jpg" alt="Second slide">
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="~/fonts/img/img-hotdeal/aa920066-1cd8-0100-8172-001794c45562.jpg" alt="Third slide">
            </div>
            <div class="carousel-item">
                <img class="d-block w-100"  style="width:1201px ; height:690px" src="~/fonts/img/img-hotdeal/bfb14e59-adcc-47b6-9bc2-fe822e4df4dc-dhk2.jpg" alt="Third slide">
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
    @*<div class="carousel_content"></div>*@
</section>

<section class="sell-1">
    <div class="container">
        <div class="row">
            @foreach (var item in product)
            {
                <div class="col-sm-6">
                    <h3>@item.TenSP</h3>
                    <img class="img-fluid" src="~/fonts/img/img-sell1/6e5db9b6-a47b-4470-b2ce-e59e2ba22b5e-Untitled-3.jpg" />

                </div>

            }
        </div>
    </div>
</section>

<section class="hot-deal">
    <div class="container">
        <div class="hot_content">
            <h1>Top Sản Phẩm Hot</h1>
            <p>Những sản phẩm thời trang hot và mới nhất</p>
        </div>
        <div class="row" style="padding-top:15px">
            <div class="col-sm-3 text-center">
                <img class="img-fluid" src="~/fonts/img/img-hotdeal/77632fb9-2169-0100-5fbb-00178e8f7adb.jpg" />
                <div class="gallery_overlay">
                    <h3><span>Sản </span>Phẩm</h3>
                    <p>Sản Phẩm Độc Quyền Từ DCD</p>
                </div>
                <h5>Áo Thun Aides Ver1 <span style="text-decoration:line-through">250k </span><span style="color:red">200k</span></h5>
            </div>
            <div class="col-sm-3 text-center">
                <img class="img-fluid" src="~/fonts/img/img-hotdeal/6bdd7372-3e26-0500-96fc-00178e8ffbc7.jpg" />
                <div class="gallery_overlay">
                    <h3><span>Sản </span>Phẩm</h3>
                    <p>Sản Phẩm Độc Quyền Từ DCD</p>
                </div>
                <h5>Áo Thun Wild Animals M3 <span style="text-decoration:line-through">185k </span><span style="color:red">148k</span></h5>
            </div>
            <div class="col-sm-3 text-center">
                <img class="img-fluid" src="~/fonts/img/img-hotdeal/9a0ed0e8-14bf-1800-c361-00178e91858d.jpg" />
                <div class="gallery_overlay">
                    <h3><span>Sản </span>Phẩm</h3>
                    <p>Sản Phẩm Độc Quyền Từ DCD</p>
                </div>
                <h5>Áo Thun Y2010 Originals M9 <span style="text-decoration:line-through">185k </span><span style="color:red">148k</span></h5>
            </div>
            <div class="col-sm-3 text-center">
                <img class="img-fluid" src="~/fonts/img/img-hotdeal/46430e55-0309-2600-a75a-00178e931170.jpg" />
                <div class="gallery_overlay">
                    <h3><span>Sản </span>Phẩm</h3>
                    <p>Sản Phẩm Độc Quyền Từ DCD</p>
                </div>
                <h5>Áo Thun Thiên Nhiên Kì Vĩ M8 <span style="text-decoration:line-through">185k </span><span style="color:red">148k</span></h5>
            </div>
        </div>
    </div>

</section>

<section class="promotion">
    <div class="container">
        <div class="promotion-content">
            <h1>Các chương trình Khuyến mãi</h1>
            <p>Đừng bỏ lỡ các chương trình khuyến mãi Hot tại Yame.vn</p>
        </div>
        <div class="row" style="text-align:center">

            <div class="col-sm-12">
                <img class="img-fluid" src="~/fonts/img/promotion/59ab70c7-e39f-0100-80cb-001785dd03e1.jpg" />
                <h3>SĂN SALE ÁO KHOÁC - ĐÓN GIÓ ĐÔNG VỀ</h3>
                <p>Thời gian: 26/12/2020 - 10/02/2021 Địa điểm: Áp dụng tại tất cả chi nhánh, không áp dụng Online</p>
            </div>
        </div>
    </div>
</section>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

CNPM/Views/Home/Quan.cshtml
@using CNPM.Models
@{
    ViewBag.Title = "Quần";
    List<SanPham> quan = ViewBag.quan;
}

<div class="container">
    
    <div class="row" style="text-align:center">
        <h2 style="color:blue; background-color:yellow"><b><i>Quần Dài</i></b></h2>
        @foreach (var i in quan)
        {
            if (i.MaDanhMuc == 4)

            {

    <div class="col-sm-3">
        <a href="@Url.Action("QuanDai","Clothes", new { id = @i.MaSP})">
            <img class="img-fluid" src="~/fonts/img/quandai/@i.HinhAnh" /> </a>
            <p>@i.TenSP</p>
    </div>
            }
        }

    </div>
    <div class="row" style="text-align:center">
        <h2 style="color:blue; background-color:yellow"><b><i>Quần Short</i></b></h2>
        @foreach (var i in quan)
        {
            if (i.MaDanhMuc == 5)
            {
    <div class="col-sm-3">
        <a href="@Url.Action("QuanShort","Clothes", new { id = @i.MaSP})"><img class="img-fluid" src="~/fonts/img/quanshort/@i.HinhAnh" /></a>
         <p>@i.TenSP</p>
    </div>
            }
        }

    </div>
   
</div>